name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Greet and count files
        env:
          PROJECT_OWNER: ${{ vars.PROJECT_OWNER }}
        run: |
          COUNT=$(find . -type f -not -path './.git/*' | wc -l)
          echo "Hello $PROJECT_OWNER, your files count are $COUNT"